### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by jerrystsai** [learn-co-curriculum/ruby-initialization#10]
This code does not work:

```
class Dog
  def breed=(breed)
    @breed
  end

  def breed
    @breed
  end
end
```

When you try to assign a breed to a Dog instance, it fails to set it.

Shouldn't the third line be: `@breed = breed`? That makes the following code work:

```
snoopy = Dog.new #=> #<Dog:0x007f970a2edfd0>
snoopy.breed #=> nil
snoopy.breed = "Beagle"
snoopy.breed #=> "Beagle"
```

Using the code in the lesson will yield this for the final line code:

```
snoopy.breed #=> nil
```

...which is wholly undesireable.

**Comment by AnnJohn** [comment]
Hi @jerrystsai sorry for the delay with this. But for immediate help with lessons, please use the Ask a Question Tool in Learn and someone will get back to you right away. Thanks!
