### ISSUE TITLE
Remove setter and getter stuff and move this lesson earlier in the curriculum

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-initialization#15]

**Comment by AnnJohn** [comment]
Hi @pletcher since @StevenNunez will be working on this, do you have any more specifics on this and at what point in this curriculum you see this being moved to? 

Thanks

**Comment by pletcher** [comment]
Actually, looking at the rest of the curriculum and how we get to this point, I think this is okay. Not sure if I had missed something earlier or what.
