### ISSUE TITLE
Lessons out of order

### ISSUE THREAD

**Issue by abourke09** [learn-co-curriculum/ruby-initialization#16]
The lesson Object Initialization introduces the concept of initialize method. It would have been really helpful if this lesson was placed before the Object Attributes Readme (which includes the initialize method before the concept is introduced). It seems like these were just placed out of order in the curriculum.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We will either adjust the lessons order or update `Object Attributes Readme` to remove references to the initialize method.

As always, thanks for contributing! 💙
