### ISSUE TITLE
Confusing syntax highlighting

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-initialization#17]
Up until this morning's OOP lecture I was very confused by methods like `def breed=(breed)`, because in the syntax highlighting on the lesson page, "breed" is colored red, but the equal sign is black. I wasn't understanding that the method name was actually "breed=" and that the black equal sign wasn't assigning a value of some kind.
<img width="263" alt="Screen Shot 2019-05-15 at 10 55 06 AM" src="https://user-images.githubusercontent.com/2370738/57785535-eefff280-76ff-11e9-9e26-8f2eb7997f64.png">

**Comment by maxwellbenton** [comment]
Hi @keithburgie,

Thank you for spotting this and providing feedback. We aren't able to adjust the way the syntax is highlighted, but we've added a note regarding this two lessons prior, where setter methods are introduced to point this issue out and emphasize the necessity of the `=`  symbol.

Thank you for contributing to a Learn lesson!
